#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgAccount.Datasource.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EGAccount")]
	public partial class dsLinqDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCDAccountNature(CDAccountNature instance);
    partial void UpdateCDAccountNature(CDAccountNature instance);
    partial void DeleteCDAccountNature(CDAccountNature instance);
    partial void InsertCDBANK(CDBANK instance);
    partial void UpdateCDBANK(CDBANK instance);
    partial void DeleteCDBANK(CDBANK instance);
    partial void InsertCDKHTAMIACOUNT(CDKHTAMIACOUNT instance);
    partial void UpdateCDKHTAMIACOUNT(CDKHTAMIACOUNT instance);
    partial void DeleteCDKHTAMIACOUNT(CDKHTAMIACOUNT instance);
    partial void InsertCDYera(CDYera instance);
    partial void UpdateCDYera(CDYera instance);
    partial void DeleteCDYera(CDYera instance);
    partial void InsertvQry001(vQry001 instance);
    partial void UpdatevQry001(vQry001 instance);
    partial void DeletevQry001(vQry001 instance);
    partial void InsertvTBLCheekNumber(vTBLCheekNumber instance);
    partial void UpdatevTBLCheekNumber(vTBLCheekNumber instance);
    partial void DeletevTBLCheekNumber(vTBLCheekNumber instance);
    partial void InsertvQry002(vQry002 instance);
    partial void UpdatevQry002(vQry002 instance);
    partial void DeletevQry002(vQry002 instance);
    partial void Insertvtblraseed(vtblraseed instance);
    partial void Updatevtblraseed(vtblraseed instance);
    partial void Deletevtblraseed(vtblraseed instance);
    partial void InsertvTBL_Accounte(vTBL_Accounte instance);
    partial void UpdatevTBL_Accounte(vTBL_Accounte instance);
    partial void DeletevTBL_Accounte(vTBL_Accounte instance);
    partial void Insertvtbleznsar(vtbleznsar instance);
    partial void Updatevtbleznsar(vtbleznsar instance);
    partial void Deletevtbleznsar(vtbleznsar instance);
    partial void InsertvTBLkazna(vTBLkazna instance);
    partial void UpdatevTBLkazna(vTBLkazna instance);
    partial void DeletevTBLkazna(vTBLkazna instance);
    partial void InsertCDkaznatype(CDkaznatype instance);
    partial void UpdateCDkaznatype(CDkaznatype instance);
    partial void DeleteCDkaznatype(CDkaznatype instance);
    partial void InsertvTBLTRAANSDETAIL(vTBLTRAANSDETAIL instance);
    partial void UpdatevTBLTRAANSDETAIL(vTBLTRAANSDETAIL instance);
    partial void DeletevTBLTRAANSDETAIL(vTBLTRAANSDETAIL instance);
    #endregion
		
		public dsLinqDataDataContext() : 
				base(global::EgAccount.Properties.Settings.Default.EGAccountConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsLinqDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CDAccountNature> CDAccountNatures
		{
			get
			{
				return this.GetTable<CDAccountNature>();
			}
		}
		
		public System.Data.Linq.Table<CDBANK> CDBANKs
		{
			get
			{
				return this.GetTable<CDBANK>();
			}
		}
		
		public System.Data.Linq.Table<CDKHTAMIACOUNT> CDKHTAMIACOUNTs
		{
			get
			{
				return this.GetTable<CDKHTAMIACOUNT>();
			}
		}
		
		public System.Data.Linq.Table<CDYera> CDYeras
		{
			get
			{
				return this.GetTable<CDYera>();
			}
		}
		
		public System.Data.Linq.Table<vQry001> vQry001s
		{
			get
			{
				return this.GetTable<vQry001>();
			}
		}
		
		public System.Data.Linq.Table<vTBLCheekNumber> vTBLCheekNumbers
		{
			get
			{
				return this.GetTable<vTBLCheekNumber>();
			}
		}
		
		public System.Data.Linq.Table<vQry002> vQry002s
		{
			get
			{
				return this.GetTable<vQry002>();
			}
		}
		
		public System.Data.Linq.Table<vtblraseed> vtblraseeds
		{
			get
			{
				return this.GetTable<vtblraseed>();
			}
		}
		
		public System.Data.Linq.Table<vTBL_Accounte> vTBL_Accountes
		{
			get
			{
				return this.GetTable<vTBL_Accounte>();
			}
		}
		
		public System.Data.Linq.Table<vtbleznsar> vtbleznsars
		{
			get
			{
				return this.GetTable<vtbleznsar>();
			}
		}
		
		public System.Data.Linq.Table<vTBLkazna> vTBLkaznas
		{
			get
			{
				return this.GetTable<vTBLkazna>();
			}
		}
		
		public System.Data.Linq.Table<CDkaznatype> CDkaznatypes
		{
			get
			{
				return this.GetTable<CDkaznatype>();
			}
		}
		
		public System.Data.Linq.Table<vTBLTRAANSDETAIL> vTBLTRAANSDETAILs
		{
			get
			{
				return this.GetTable<vTBLTRAANSDETAIL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CDAccountNature")]
	public partial class CDAccountNature : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _AccNatueID;
		
		private string _AccNatueName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccNatueIDChanging(byte value);
    partial void OnAccNatueIDChanged();
    partial void OnAccNatueNameChanging(string value);
    partial void OnAccNatueNameChanged();
    #endregion
		
		public CDAccountNature()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNatueID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte AccNatueID
		{
			get
			{
				return this._AccNatueID;
			}
			set
			{
				if ((this._AccNatueID != value))
				{
					this.OnAccNatueIDChanging(value);
					this.SendPropertyChanging();
					this._AccNatueID = value;
					this.SendPropertyChanged("AccNatueID");
					this.OnAccNatueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNatueName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AccNatueName
		{
			get
			{
				return this._AccNatueName;
			}
			set
			{
				if ((this._AccNatueName != value))
				{
					this.OnAccNatueNameChanging(value);
					this.SendPropertyChanging();
					this._AccNatueName = value;
					this.SendPropertyChanged("AccNatueName");
					this.OnAccNatueNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CDBANK")]
	public partial class CDBANK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BankAcountID;
		
		private string _BankName;
		
		private string _BankAcountNO;
		
		private string _BankAcountName;
		
		private string _BankAddess;
		
		private string _BankTel1;
		
		private string _BankTel2;
		
		private string _BankFax;
		
		private string _Bremark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBankAcountIDChanging(int value);
    partial void OnBankAcountIDChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankAcountNOChanging(string value);
    partial void OnBankAcountNOChanged();
    partial void OnBankAcountNameChanging(string value);
    partial void OnBankAcountNameChanged();
    partial void OnBankAddessChanging(string value);
    partial void OnBankAddessChanged();
    partial void OnBankTel1Changing(string value);
    partial void OnBankTel1Changed();
    partial void OnBankTel2Changing(string value);
    partial void OnBankTel2Changed();
    partial void OnBankFaxChanging(string value);
    partial void OnBankFaxChanged();
    partial void OnBremarkChanging(string value);
    partial void OnBremarkChanged();
    #endregion
		
		public CDBANK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BankAcountID
		{
			get
			{
				return this._BankAcountID;
			}
			set
			{
				if ((this._BankAcountID != value))
				{
					this.OnBankAcountIDChanging(value);
					this.SendPropertyChanging();
					this._BankAcountID = value;
					this.SendPropertyChanged("BankAcountID");
					this.OnBankAcountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountNO
		{
			get
			{
				return this._BankAcountNO;
			}
			set
			{
				if ((this._BankAcountNO != value))
				{
					this.OnBankAcountNOChanging(value);
					this.SendPropertyChanging();
					this._BankAcountNO = value;
					this.SendPropertyChanged("BankAcountNO");
					this.OnBankAcountNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountName
		{
			get
			{
				return this._BankAcountName;
			}
			set
			{
				if ((this._BankAcountName != value))
				{
					this.OnBankAcountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAcountName = value;
					this.SendPropertyChanged("BankAcountName");
					this.OnBankAcountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAddess", DbType="NVarChar(100)")]
		public string BankAddess
		{
			get
			{
				return this._BankAddess;
			}
			set
			{
				if ((this._BankAddess != value))
				{
					this.OnBankAddessChanging(value);
					this.SendPropertyChanging();
					this._BankAddess = value;
					this.SendPropertyChanged("BankAddess");
					this.OnBankAddessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankTel1", DbType="NVarChar(14)")]
		public string BankTel1
		{
			get
			{
				return this._BankTel1;
			}
			set
			{
				if ((this._BankTel1 != value))
				{
					this.OnBankTel1Changing(value);
					this.SendPropertyChanging();
					this._BankTel1 = value;
					this.SendPropertyChanged("BankTel1");
					this.OnBankTel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankTel2", DbType="NVarChar(14)")]
		public string BankTel2
		{
			get
			{
				return this._BankTel2;
			}
			set
			{
				if ((this._BankTel2 != value))
				{
					this.OnBankTel2Changing(value);
					this.SendPropertyChanging();
					this._BankTel2 = value;
					this.SendPropertyChanged("BankTel2");
					this.OnBankTel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankFax", DbType="NVarChar(14)")]
		public string BankFax
		{
			get
			{
				return this._BankFax;
			}
			set
			{
				if ((this._BankFax != value))
				{
					this.OnBankFaxChanging(value);
					this.SendPropertyChanging();
					this._BankFax = value;
					this.SendPropertyChanged("BankFax");
					this.OnBankFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bremark", DbType="NVarChar(100)")]
		public string Bremark
		{
			get
			{
				return this._Bremark;
			}
			set
			{
				if ((this._Bremark != value))
				{
					this.OnBremarkChanging(value);
					this.SendPropertyChanging();
					this._Bremark = value;
					this.SendPropertyChanged("Bremark");
					this.OnBremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CDKHTAMIACOUNT")]
	public partial class CDKHTAMIACOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _KhtamiaccID;
		
		private string _KhtamiaccName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhtamiaccIDChanging(byte value);
    partial void OnKhtamiaccIDChanged();
    partial void OnKhtamiaccNameChanging(string value);
    partial void OnKhtamiaccNameChanged();
    #endregion
		
		public CDKHTAMIACOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhtamiaccID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte KhtamiaccID
		{
			get
			{
				return this._KhtamiaccID;
			}
			set
			{
				if ((this._KhtamiaccID != value))
				{
					this.OnKhtamiaccIDChanging(value);
					this.SendPropertyChanging();
					this._KhtamiaccID = value;
					this.SendPropertyChanged("KhtamiaccID");
					this.OnKhtamiaccIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhtamiaccName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string KhtamiaccName
		{
			get
			{
				return this._KhtamiaccName;
			}
			set
			{
				if ((this._KhtamiaccName != value))
				{
					this.OnKhtamiaccNameChanging(value);
					this.SendPropertyChanging();
					this._KhtamiaccName = value;
					this.SendPropertyChanged("KhtamiaccName");
					this.OnKhtamiaccNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CDYeras")]
	public partial class CDYera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _YearID;
		
		private string _YearName;
		
		private System.DateTime _YStartDate;
		
		private System.DateTime _YEndDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYearIDChanging(byte value);
    partial void OnYearIDChanged();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnYStartDateChanging(System.DateTime value);
    partial void OnYStartDateChanged();
    partial void OnYEndDateChanging(System.DateTime value);
    partial void OnYEndDateChanged();
    #endregion
		
		public CDYera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte YearID
		{
			get
			{
				return this._YearID;
			}
			set
			{
				if ((this._YearID != value))
				{
					this.OnYearIDChanging(value);
					this.SendPropertyChanging();
					this._YearID = value;
					this.SendPropertyChanged("YearID");
					this.OnYearIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YStartDate", DbType="DateTime NOT NULL")]
		public System.DateTime YStartDate
		{
			get
			{
				return this._YStartDate;
			}
			set
			{
				if ((this._YStartDate != value))
				{
					this.OnYStartDateChanging(value);
					this.SendPropertyChanging();
					this._YStartDate = value;
					this.SendPropertyChanged("YStartDate");
					this.OnYStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime YEndDate
		{
			get
			{
				return this._YEndDate;
			}
			set
			{
				if ((this._YEndDate != value))
				{
					this.OnYEndDateChanging(value);
					this.SendPropertyChanging();
					this._YEndDate = value;
					this.SendPropertyChanged("YEndDate");
					this.OnYEndDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry001")]
	public partial class vQry001 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _YearName;
		
		private System.Nullable<System.DateTime> _KIEDDATE;
		
		private string _KIEDDESC;
		
		private System.Nullable<bool> _trhel;
		
		private int _TRANSID;
		
		private byte _YearID;
		
		private System.Nullable<int> _KIEDNO;
		
		private System.Nullable<int> _KIEDDAFTRYNO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnKIEDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKIEDDATEChanged();
    partial void OnKIEDDESCChanging(string value);
    partial void OnKIEDDESCChanged();
    partial void OntrhelChanging(System.Nullable<bool> value);
    partial void OntrhelChanged();
    partial void OnTRANSIDChanging(int value);
    partial void OnTRANSIDChanged();
    partial void OnYearIDChanging(byte value);
    partial void OnYearIDChanged();
    partial void OnKIEDNOChanging(System.Nullable<int> value);
    partial void OnKIEDNOChanged();
    partial void OnKIEDDAFTRYNOChanging(System.Nullable<int> value);
    partial void OnKIEDDAFTRYNOChanged();
    #endregion
		
		public vQry001()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KIEDDATE
		{
			get
			{
				return this._KIEDDATE;
			}
			set
			{
				if ((this._KIEDDATE != value))
				{
					this.OnKIEDDATEChanging(value);
					this.SendPropertyChanging();
					this._KIEDDATE = value;
					this.SendPropertyChanged("KIEDDATE");
					this.OnKIEDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDESC", DbType="NVarChar(100)")]
		public string KIEDDESC
		{
			get
			{
				return this._KIEDDESC;
			}
			set
			{
				if ((this._KIEDDESC != value))
				{
					this.OnKIEDDESCChanging(value);
					this.SendPropertyChanging();
					this._KIEDDESC = value;
					this.SendPropertyChanged("KIEDDESC");
					this.OnKIEDDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trhel", DbType="Bit")]
		public System.Nullable<bool> trhel
		{
			get
			{
				return this._trhel;
			}
			set
			{
				if ((this._trhel != value))
				{
					this.OntrhelChanging(value);
					this.SendPropertyChanging();
					this._trhel = value;
					this.SendPropertyChanged("trhel");
					this.OntrhelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRANSID
		{
			get
			{
				return this._TRANSID;
			}
			set
			{
				if ((this._TRANSID != value))
				{
					this.OnTRANSIDChanging(value);
					this.SendPropertyChanging();
					this._TRANSID = value;
					this.SendPropertyChanged("TRANSID");
					this.OnTRANSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearID", DbType="TinyInt NOT NULL")]
		public byte YearID
		{
			get
			{
				return this._YearID;
			}
			set
			{
				if ((this._YearID != value))
				{
					this.OnYearIDChanging(value);
					this.SendPropertyChanging();
					this._YearID = value;
					this.SendPropertyChanged("YearID");
					this.OnYearIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDNO", DbType="Int")]
		public System.Nullable<int> KIEDNO
		{
			get
			{
				return this._KIEDNO;
			}
			set
			{
				if ((this._KIEDNO != value))
				{
					this.OnKIEDNOChanging(value);
					this.SendPropertyChanging();
					this._KIEDNO = value;
					this.SendPropertyChanged("KIEDNO");
					this.OnKIEDNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDAFTRYNO", DbType="Int")]
		public System.Nullable<int> KIEDDAFTRYNO
		{
			get
			{
				return this._KIEDDAFTRYNO;
			}
			set
			{
				if ((this._KIEDDAFTRYNO != value))
				{
					this.OnKIEDDAFTRYNOChanging(value);
					this.SendPropertyChanging();
					this._KIEDDAFTRYNO = value;
					this.SendPropertyChanged("KIEDDAFTRYNO");
					this.OnKIEDDAFTRYNOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLCheekNumbers")]
	public partial class vTBLCheekNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CheekAuto;
		
		private int _BankAcountID;
		
		private long _CheekNumber;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private string _UserName;
		
		private string _BankName;
		
		private string _BankAcountName;
		
		private string _BankAcountNO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCheekAutoChanging(long value);
    partial void OnCheekAutoChanged();
    partial void OnBankAcountIDChanging(int value);
    partial void OnBankAcountIDChanged();
    partial void OnCheekNumberChanging(long value);
    partial void OnCheekNumberChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankAcountNameChanging(string value);
    partial void OnBankAcountNameChanged();
    partial void OnBankAcountNOChanging(string value);
    partial void OnBankAcountNOChanged();
    #endregion
		
		public vTBLCheekNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekAuto", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CheekAuto
		{
			get
			{
				return this._CheekAuto;
			}
			set
			{
				if ((this._CheekAuto != value))
				{
					this.OnCheekAutoChanging(value);
					this.SendPropertyChanging();
					this._CheekAuto = value;
					this.SendPropertyChanged("CheekAuto");
					this.OnCheekAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountID", DbType="Int NOT NULL")]
		public int BankAcountID
		{
			get
			{
				return this._BankAcountID;
			}
			set
			{
				if ((this._BankAcountID != value))
				{
					this.OnBankAcountIDChanging(value);
					this.SendPropertyChanging();
					this._BankAcountID = value;
					this.SendPropertyChanged("BankAcountID");
					this.OnBankAcountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekNumber", DbType="BigInt NOT NULL")]
		public long CheekNumber
		{
			get
			{
				return this._CheekNumber;
			}
			set
			{
				if ((this._CheekNumber != value))
				{
					this.OnCheekNumberChanging(value);
					this.SendPropertyChanging();
					this._CheekNumber = value;
					this.SendPropertyChanged("CheekNumber");
					this.OnCheekNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountName
		{
			get
			{
				return this._BankAcountName;
			}
			set
			{
				if ((this._BankAcountName != value))
				{
					this.OnBankAcountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAcountName = value;
					this.SendPropertyChanged("BankAcountName");
					this.OnBankAcountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountNO
		{
			get
			{
				return this._BankAcountNO;
			}
			set
			{
				if ((this._BankAcountNO != value))
				{
					this.OnBankAcountNOChanging(value);
					this.SendPropertyChanging();
					this._BankAcountNO = value;
					this.SendPropertyChanged("BankAcountNO");
					this.OnBankAcountNOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vQry002")]
	public partial class vQry002 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CheekAuto;
		
		private int _BankAcountID;
		
		private long _CheekNumber;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private string _UserName;
		
		private string _BankName;
		
		private string _BankAcountName;
		
		private string _BankAcountNO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCheekAutoChanging(long value);
    partial void OnCheekAutoChanged();
    partial void OnBankAcountIDChanging(int value);
    partial void OnBankAcountIDChanged();
    partial void OnCheekNumberChanging(long value);
    partial void OnCheekNumberChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankAcountNameChanging(string value);
    partial void OnBankAcountNameChanged();
    partial void OnBankAcountNOChanging(string value);
    partial void OnBankAcountNOChanged();
    #endregion
		
		public vQry002()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekAuto", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CheekAuto
		{
			get
			{
				return this._CheekAuto;
			}
			set
			{
				if ((this._CheekAuto != value))
				{
					this.OnCheekAutoChanging(value);
					this.SendPropertyChanging();
					this._CheekAuto = value;
					this.SendPropertyChanged("CheekAuto");
					this.OnCheekAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountID", DbType="Int NOT NULL")]
		public int BankAcountID
		{
			get
			{
				return this._BankAcountID;
			}
			set
			{
				if ((this._BankAcountID != value))
				{
					this.OnBankAcountIDChanging(value);
					this.SendPropertyChanging();
					this._BankAcountID = value;
					this.SendPropertyChanged("BankAcountID");
					this.OnBankAcountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekNumber", DbType="BigInt NOT NULL")]
		public long CheekNumber
		{
			get
			{
				return this._CheekNumber;
			}
			set
			{
				if ((this._CheekNumber != value))
				{
					this.OnCheekNumberChanging(value);
					this.SendPropertyChanging();
					this._CheekNumber = value;
					this.SendPropertyChanged("CheekNumber");
					this.OnCheekNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountName
		{
			get
			{
				return this._BankAcountName;
			}
			set
			{
				if ((this._BankAcountName != value))
				{
					this.OnBankAcountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAcountName = value;
					this.SendPropertyChanged("BankAcountName");
					this.OnBankAcountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountNO
		{
			get
			{
				return this._BankAcountNO;
			}
			set
			{
				if ((this._BankAcountNO != value))
				{
					this.OnBankAcountNOChanging(value);
					this.SendPropertyChanging();
					this._BankAcountNO = value;
					this.SendPropertyChanged("BankAcountNO");
					this.OnBankAcountNOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vtblraseed")]
	public partial class vtblraseed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountId;
		
		private byte _YearID;
		
		private double _raseedmadeen;
		
		private double _raseeddaen;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private string _UserName;
		
		private string _YearName;
		
		private string _AccountDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIdChanging(int value);
    partial void OnAccountIdChanged();
    partial void OnYearIDChanging(byte value);
    partial void OnYearIDChanged();
    partial void OnraseedmadeenChanging(double value);
    partial void OnraseedmadeenChanged();
    partial void OnraseeddaenChanging(double value);
    partial void OnraseeddaenChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnAccountDesChanging(string value);
    partial void OnAccountDesChanged();
    #endregion
		
		public vtblraseed()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte YearID
		{
			get
			{
				return this._YearID;
			}
			set
			{
				if ((this._YearID != value))
				{
					this.OnYearIDChanging(value);
					this.SendPropertyChanging();
					this._YearID = value;
					this.SendPropertyChanged("YearID");
					this.OnYearIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raseedmadeen", DbType="Float NOT NULL")]
		public double raseedmadeen
		{
			get
			{
				return this._raseedmadeen;
			}
			set
			{
				if ((this._raseedmadeen != value))
				{
					this.OnraseedmadeenChanging(value);
					this.SendPropertyChanging();
					this._raseedmadeen = value;
					this.SendPropertyChanged("raseedmadeen");
					this.OnraseedmadeenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raseeddaen", DbType="Float NOT NULL")]
		public double raseeddaen
		{
			get
			{
				return this._raseeddaen;
			}
			set
			{
				if ((this._raseeddaen != value))
				{
					this.OnraseeddaenChanging(value);
					this.SendPropertyChanging();
					this._raseeddaen = value;
					this.SendPropertyChanged("raseeddaen");
					this.OnraseeddaenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountDes", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AccountDes
		{
			get
			{
				return this._AccountDes;
			}
			set
			{
				if ((this._AccountDes != value))
				{
					this.OnAccountDesChanging(value);
					this.SendPropertyChanging();
					this._AccountDes = value;
					this.SendPropertyChanged("AccountDes");
					this.OnAccountDesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBL_Accountes")]
	public partial class vTBL_Accounte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountId;
		
		private int _AccountTreeId;
		
		private System.Nullable<int> _PairantAccount;
		
		private string _AccountDes;
		
		private System.Nullable<byte> _AccountSort;
		
		private System.Nullable<byte> _KhtamiaccID;
		
		private System.Nullable<byte> _AccNatueID;
		
		private System.Nullable<double> _AccountBudget;
		
		private System.Nullable<double> _CuurentMadeen;
		
		private System.Nullable<double> _CuurentDaien;
		
		private System.Nullable<bool> _aznsarf;
		
		private string _KhtamiaccName;
		
		private string _AccNatueName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIdChanging(int value);
    partial void OnAccountIdChanged();
    partial void OnAccountTreeIdChanging(int value);
    partial void OnAccountTreeIdChanged();
    partial void OnPairantAccountChanging(System.Nullable<int> value);
    partial void OnPairantAccountChanged();
    partial void OnAccountDesChanging(string value);
    partial void OnAccountDesChanged();
    partial void OnAccountSortChanging(System.Nullable<byte> value);
    partial void OnAccountSortChanged();
    partial void OnKhtamiaccIDChanging(System.Nullable<byte> value);
    partial void OnKhtamiaccIDChanged();
    partial void OnAccNatueIDChanging(System.Nullable<byte> value);
    partial void OnAccNatueIDChanged();
    partial void OnAccountBudgetChanging(System.Nullable<double> value);
    partial void OnAccountBudgetChanged();
    partial void OnCuurentMadeenChanging(System.Nullable<double> value);
    partial void OnCuurentMadeenChanged();
    partial void OnCuurentDaienChanging(System.Nullable<double> value);
    partial void OnCuurentDaienChanged();
    partial void OnaznsarfChanging(System.Nullable<bool> value);
    partial void OnaznsarfChanged();
    partial void OnKhtamiaccNameChanging(string value);
    partial void OnKhtamiaccNameChanged();
    partial void OnAccNatueNameChanging(string value);
    partial void OnAccNatueNameChanged();
    #endregion
		
		public vTBL_Accounte()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountTreeId", DbType="Int NOT NULL")]
		public int AccountTreeId
		{
			get
			{
				return this._AccountTreeId;
			}
			set
			{
				if ((this._AccountTreeId != value))
				{
					this.OnAccountTreeIdChanging(value);
					this.SendPropertyChanging();
					this._AccountTreeId = value;
					this.SendPropertyChanged("AccountTreeId");
					this.OnAccountTreeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PairantAccount", DbType="Int")]
		public System.Nullable<int> PairantAccount
		{
			get
			{
				return this._PairantAccount;
			}
			set
			{
				if ((this._PairantAccount != value))
				{
					this.OnPairantAccountChanging(value);
					this.SendPropertyChanging();
					this._PairantAccount = value;
					this.SendPropertyChanged("PairantAccount");
					this.OnPairantAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountDes", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AccountDes
		{
			get
			{
				return this._AccountDes;
			}
			set
			{
				if ((this._AccountDes != value))
				{
					this.OnAccountDesChanging(value);
					this.SendPropertyChanging();
					this._AccountDes = value;
					this.SendPropertyChanged("AccountDes");
					this.OnAccountDesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountSort", DbType="TinyInt")]
		public System.Nullable<byte> AccountSort
		{
			get
			{
				return this._AccountSort;
			}
			set
			{
				if ((this._AccountSort != value))
				{
					this.OnAccountSortChanging(value);
					this.SendPropertyChanging();
					this._AccountSort = value;
					this.SendPropertyChanged("AccountSort");
					this.OnAccountSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhtamiaccID", DbType="TinyInt")]
		public System.Nullable<byte> KhtamiaccID
		{
			get
			{
				return this._KhtamiaccID;
			}
			set
			{
				if ((this._KhtamiaccID != value))
				{
					this.OnKhtamiaccIDChanging(value);
					this.SendPropertyChanging();
					this._KhtamiaccID = value;
					this.SendPropertyChanged("KhtamiaccID");
					this.OnKhtamiaccIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNatueID", DbType="TinyInt")]
		public System.Nullable<byte> AccNatueID
		{
			get
			{
				return this._AccNatueID;
			}
			set
			{
				if ((this._AccNatueID != value))
				{
					this.OnAccNatueIDChanging(value);
					this.SendPropertyChanging();
					this._AccNatueID = value;
					this.SendPropertyChanged("AccNatueID");
					this.OnAccNatueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBudget", DbType="Float")]
		public System.Nullable<double> AccountBudget
		{
			get
			{
				return this._AccountBudget;
			}
			set
			{
				if ((this._AccountBudget != value))
				{
					this.OnAccountBudgetChanging(value);
					this.SendPropertyChanging();
					this._AccountBudget = value;
					this.SendPropertyChanged("AccountBudget");
					this.OnAccountBudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuurentMadeen", DbType="Float")]
		public System.Nullable<double> CuurentMadeen
		{
			get
			{
				return this._CuurentMadeen;
			}
			set
			{
				if ((this._CuurentMadeen != value))
				{
					this.OnCuurentMadeenChanging(value);
					this.SendPropertyChanging();
					this._CuurentMadeen = value;
					this.SendPropertyChanged("CuurentMadeen");
					this.OnCuurentMadeenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuurentDaien", DbType="Float")]
		public System.Nullable<double> CuurentDaien
		{
			get
			{
				return this._CuurentDaien;
			}
			set
			{
				if ((this._CuurentDaien != value))
				{
					this.OnCuurentDaienChanging(value);
					this.SendPropertyChanging();
					this._CuurentDaien = value;
					this.SendPropertyChanged("CuurentDaien");
					this.OnCuurentDaienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aznsarf", DbType="Bit")]
		public System.Nullable<bool> aznsarf
		{
			get
			{
				return this._aznsarf;
			}
			set
			{
				if ((this._aznsarf != value))
				{
					this.OnaznsarfChanging(value);
					this.SendPropertyChanging();
					this._aznsarf = value;
					this.SendPropertyChanged("aznsarf");
					this.OnaznsarfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhtamiaccName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string KhtamiaccName
		{
			get
			{
				return this._KhtamiaccName;
			}
			set
			{
				if ((this._KhtamiaccName != value))
				{
					this.OnKhtamiaccNameChanging(value);
					this.SendPropertyChanging();
					this._KhtamiaccName = value;
					this.SendPropertyChanged("KhtamiaccName");
					this.OnKhtamiaccNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNatueName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string AccNatueName
		{
			get
			{
				return this._AccNatueName;
			}
			set
			{
				if ((this._AccNatueName != value))
				{
					this.OnAccNatueNameChanging(value);
					this.SendPropertyChanging();
					this._AccNatueName = value;
					this.SendPropertyChanged("AccNatueName");
					this.OnAccNatueNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vtbleznsars")]
	public partial class vtbleznsar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _eznsarfno;
		
		private int _TRANSID;
		
		private long _CheekAuto;
		
		private byte _cheekstateid;
		
		private string _mostafeed;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private string _ezndes;
		
		private long _CheekNumber;
		
		private string _BankName;
		
		private string _BankAcountName;
		
		private string _UserName;
		
		private string _YearName;
		
		private System.Nullable<System.DateTime> _KIEDDATE;
		
		private string _KIEDDESC;
		
		private System.Nullable<bool> _trhel;
		
		private string _morfacat;
		
		private System.Nullable<System.DateTime> _ezndate;
		
		private System.Nullable<bool> _show;
		
		private System.Nullable<bool> _tsleem;
		
		private string _mostlem;
		
		private System.Nullable<System.DateTime> _tsleemdate;
		
		private System.Nullable<int> _usertasleem;
		
		private System.Nullable<System.DateTime> _dateintasleem;
		
		private string _UserNameTasleem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OneznsarfnoChanging(long value);
    partial void OneznsarfnoChanged();
    partial void OnTRANSIDChanging(int value);
    partial void OnTRANSIDChanged();
    partial void OnCheekAutoChanging(long value);
    partial void OnCheekAutoChanged();
    partial void OncheekstateidChanging(byte value);
    partial void OncheekstateidChanged();
    partial void OnmostafeedChanging(string value);
    partial void OnmostafeedChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnezndesChanging(string value);
    partial void OnezndesChanged();
    partial void OnCheekNumberChanging(long value);
    partial void OnCheekNumberChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankAcountNameChanging(string value);
    partial void OnBankAcountNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnKIEDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKIEDDATEChanged();
    partial void OnKIEDDESCChanging(string value);
    partial void OnKIEDDESCChanged();
    partial void OntrhelChanging(System.Nullable<bool> value);
    partial void OntrhelChanged();
    partial void OnmorfacatChanging(string value);
    partial void OnmorfacatChanged();
    partial void OnezndateChanging(System.Nullable<System.DateTime> value);
    partial void OnezndateChanged();
    partial void OnshowChanging(System.Nullable<bool> value);
    partial void OnshowChanged();
    partial void OntsleemChanging(System.Nullable<bool> value);
    partial void OntsleemChanged();
    partial void OnmostlemChanging(string value);
    partial void OnmostlemChanged();
    partial void OntsleemdateChanging(System.Nullable<System.DateTime> value);
    partial void OntsleemdateChanged();
    partial void OnusertasleemChanging(System.Nullable<int> value);
    partial void OnusertasleemChanged();
    partial void OndateintasleemChanging(System.Nullable<System.DateTime> value);
    partial void OndateintasleemChanged();
    partial void OnUserNameTasleemChanging(string value);
    partial void OnUserNameTasleemChanged();
    #endregion
		
		public vtbleznsar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eznsarfno", DbType="BigInt NOT NULL")]
		public long eznsarfno
		{
			get
			{
				return this._eznsarfno;
			}
			set
			{
				if ((this._eznsarfno != value))
				{
					this.OneznsarfnoChanging(value);
					this.SendPropertyChanging();
					this._eznsarfno = value;
					this.SendPropertyChanged("eznsarfno");
					this.OneznsarfnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRANSID
		{
			get
			{
				return this._TRANSID;
			}
			set
			{
				if ((this._TRANSID != value))
				{
					this.OnTRANSIDChanging(value);
					this.SendPropertyChanging();
					this._TRANSID = value;
					this.SendPropertyChanged("TRANSID");
					this.OnTRANSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekAuto", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CheekAuto
		{
			get
			{
				return this._CheekAuto;
			}
			set
			{
				if ((this._CheekAuto != value))
				{
					this.OnCheekAutoChanging(value);
					this.SendPropertyChanging();
					this._CheekAuto = value;
					this.SendPropertyChanged("CheekAuto");
					this.OnCheekAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cheekstateid", DbType="TinyInt NOT NULL")]
		public byte cheekstateid
		{
			get
			{
				return this._cheekstateid;
			}
			set
			{
				if ((this._cheekstateid != value))
				{
					this.OncheekstateidChanging(value);
					this.SendPropertyChanging();
					this._cheekstateid = value;
					this.SendPropertyChanged("cheekstateid");
					this.OncheekstateidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostafeed", DbType="NVarChar(100)")]
		public string mostafeed
		{
			get
			{
				return this._mostafeed;
			}
			set
			{
				if ((this._mostafeed != value))
				{
					this.OnmostafeedChanging(value);
					this.SendPropertyChanging();
					this._mostafeed = value;
					this.SendPropertyChanged("mostafeed");
					this.OnmostafeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ezndes", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ezndes
		{
			get
			{
				return this._ezndes;
			}
			set
			{
				if ((this._ezndes != value))
				{
					this.OnezndesChanging(value);
					this.SendPropertyChanging();
					this._ezndes = value;
					this.SendPropertyChanged("ezndes");
					this.OnezndesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheekNumber", DbType="BigInt NOT NULL")]
		public long CheekNumber
		{
			get
			{
				return this._CheekNumber;
			}
			set
			{
				if ((this._CheekNumber != value))
				{
					this.OnCheekNumberChanging(value);
					this.SendPropertyChanging();
					this._CheekNumber = value;
					this.SendPropertyChanged("CheekNumber");
					this.OnCheekNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAcountName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BankAcountName
		{
			get
			{
				return this._BankAcountName;
			}
			set
			{
				if ((this._BankAcountName != value))
				{
					this.OnBankAcountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAcountName = value;
					this.SendPropertyChanged("BankAcountName");
					this.OnBankAcountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KIEDDATE
		{
			get
			{
				return this._KIEDDATE;
			}
			set
			{
				if ((this._KIEDDATE != value))
				{
					this.OnKIEDDATEChanging(value);
					this.SendPropertyChanging();
					this._KIEDDATE = value;
					this.SendPropertyChanged("KIEDDATE");
					this.OnKIEDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDESC", DbType="NVarChar(100)")]
		public string KIEDDESC
		{
			get
			{
				return this._KIEDDESC;
			}
			set
			{
				if ((this._KIEDDESC != value))
				{
					this.OnKIEDDESCChanging(value);
					this.SendPropertyChanging();
					this._KIEDDESC = value;
					this.SendPropertyChanged("KIEDDESC");
					this.OnKIEDDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trhel", DbType="Bit")]
		public System.Nullable<bool> trhel
		{
			get
			{
				return this._trhel;
			}
			set
			{
				if ((this._trhel != value))
				{
					this.OntrhelChanging(value);
					this.SendPropertyChanging();
					this._trhel = value;
					this.SendPropertyChanged("trhel");
					this.OntrhelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_morfacat", DbType="NVarChar(250)")]
		public string morfacat
		{
			get
			{
				return this._morfacat;
			}
			set
			{
				if ((this._morfacat != value))
				{
					this.OnmorfacatChanging(value);
					this.SendPropertyChanging();
					this._morfacat = value;
					this.SendPropertyChanged("morfacat");
					this.OnmorfacatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ezndate", DbType="Date")]
		public System.Nullable<System.DateTime> ezndate
		{
			get
			{
				return this._ezndate;
			}
			set
			{
				if ((this._ezndate != value))
				{
					this.OnezndateChanging(value);
					this.SendPropertyChanging();
					this._ezndate = value;
					this.SendPropertyChanged("ezndate");
					this.OnezndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show", DbType="Bit")]
		public System.Nullable<bool> show
		{
			get
			{
				return this._show;
			}
			set
			{
				if ((this._show != value))
				{
					this.OnshowChanging(value);
					this.SendPropertyChanging();
					this._show = value;
					this.SendPropertyChanged("show");
					this.OnshowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsleem", DbType="Bit")]
		public System.Nullable<bool> tsleem
		{
			get
			{
				return this._tsleem;
			}
			set
			{
				if ((this._tsleem != value))
				{
					this.OntsleemChanging(value);
					this.SendPropertyChanging();
					this._tsleem = value;
					this.SendPropertyChanged("tsleem");
					this.OntsleemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostlem", DbType="NVarChar(50)")]
		public string mostlem
		{
			get
			{
				return this._mostlem;
			}
			set
			{
				if ((this._mostlem != value))
				{
					this.OnmostlemChanging(value);
					this.SendPropertyChanging();
					this._mostlem = value;
					this.SendPropertyChanged("mostlem");
					this.OnmostlemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsleemdate", DbType="Date")]
		public System.Nullable<System.DateTime> tsleemdate
		{
			get
			{
				return this._tsleemdate;
			}
			set
			{
				if ((this._tsleemdate != value))
				{
					this.OntsleemdateChanging(value);
					this.SendPropertyChanging();
					this._tsleemdate = value;
					this.SendPropertyChanged("tsleemdate");
					this.OntsleemdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertasleem", DbType="Int")]
		public System.Nullable<int> usertasleem
		{
			get
			{
				return this._usertasleem;
			}
			set
			{
				if ((this._usertasleem != value))
				{
					this.OnusertasleemChanging(value);
					this.SendPropertyChanging();
					this._usertasleem = value;
					this.SendPropertyChanged("usertasleem");
					this.OnusertasleemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateintasleem", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateintasleem
		{
			get
			{
				return this._dateintasleem;
			}
			set
			{
				if ((this._dateintasleem != value))
				{
					this.OndateintasleemChanging(value);
					this.SendPropertyChanging();
					this._dateintasleem = value;
					this.SendPropertyChanged("dateintasleem");
					this.OndateintasleemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameTasleem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserNameTasleem
		{
			get
			{
				return this._UserNameTasleem;
			}
			set
			{
				if ((this._UserNameTasleem != value))
				{
					this.OnUserNameTasleemChanging(value);
					this.SendPropertyChanging();
					this._UserNameTasleem = value;
					this.SendPropertyChanged("UserNameTasleem");
					this.OnUserNameTasleemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLkazna")]
	public partial class vTBLkazna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _actionid;
		
		private byte _kaznatypeid;
		
		private int _eznnumber;
		
		private System.DateTime _actiondate;
		
		private double _actionmony;
		
		private int _acountid;
		
		private string _mostafeed;
		
		private string _bean;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private bool _closed;
		
		private string _kaznatype;
		
		private string _AccountDes;
		
		private string _UserName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnactionidChanging(int value);
    partial void OnactionidChanged();
    partial void OnkaznatypeidChanging(byte value);
    partial void OnkaznatypeidChanged();
    partial void OneznnumberChanging(int value);
    partial void OneznnumberChanged();
    partial void OnactiondateChanging(System.DateTime value);
    partial void OnactiondateChanged();
    partial void OnactionmonyChanging(double value);
    partial void OnactionmonyChanged();
    partial void OnacountidChanging(int value);
    partial void OnacountidChanged();
    partial void OnmostafeedChanging(string value);
    partial void OnmostafeedChanged();
    partial void OnbeanChanging(string value);
    partial void OnbeanChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnclosedChanging(bool value);
    partial void OnclosedChanged();
    partial void OnkaznatypeChanging(string value);
    partial void OnkaznatypeChanged();
    partial void OnAccountDesChanging(string value);
    partial void OnAccountDesChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public vTBLkazna()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int actionid
		{
			get
			{
				return this._actionid;
			}
			set
			{
				if ((this._actionid != value))
				{
					this.OnactionidChanging(value);
					this.SendPropertyChanging();
					this._actionid = value;
					this.SendPropertyChanged("actionid");
					this.OnactionidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaznatypeid", DbType="TinyInt NOT NULL")]
		public byte kaznatypeid
		{
			get
			{
				return this._kaznatypeid;
			}
			set
			{
				if ((this._kaznatypeid != value))
				{
					this.OnkaznatypeidChanging(value);
					this.SendPropertyChanging();
					this._kaznatypeid = value;
					this.SendPropertyChanged("kaznatypeid");
					this.OnkaznatypeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eznnumber", DbType="Int NOT NULL")]
		public int eznnumber
		{
			get
			{
				return this._eznnumber;
			}
			set
			{
				if ((this._eznnumber != value))
				{
					this.OneznnumberChanging(value);
					this.SendPropertyChanging();
					this._eznnumber = value;
					this.SendPropertyChanged("eznnumber");
					this.OneznnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actiondate", DbType="Date NOT NULL")]
		public System.DateTime actiondate
		{
			get
			{
				return this._actiondate;
			}
			set
			{
				if ((this._actiondate != value))
				{
					this.OnactiondateChanging(value);
					this.SendPropertyChanging();
					this._actiondate = value;
					this.SendPropertyChanged("actiondate");
					this.OnactiondateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionmony", DbType="Float NOT NULL")]
		public double actionmony
		{
			get
			{
				return this._actionmony;
			}
			set
			{
				if ((this._actionmony != value))
				{
					this.OnactionmonyChanging(value);
					this.SendPropertyChanging();
					this._actionmony = value;
					this.SendPropertyChanged("actionmony");
					this.OnactionmonyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acountid", DbType="Int NOT NULL")]
		public int acountid
		{
			get
			{
				return this._acountid;
			}
			set
			{
				if ((this._acountid != value))
				{
					this.OnacountidChanging(value);
					this.SendPropertyChanging();
					this._acountid = value;
					this.SendPropertyChanged("acountid");
					this.OnacountidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostafeed", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string mostafeed
		{
			get
			{
				return this._mostafeed;
			}
			set
			{
				if ((this._mostafeed != value))
				{
					this.OnmostafeedChanging(value);
					this.SendPropertyChanging();
					this._mostafeed = value;
					this.SendPropertyChanged("mostafeed");
					this.OnmostafeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bean", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string bean
		{
			get
			{
				return this._bean;
			}
			set
			{
				if ((this._bean != value))
				{
					this.OnbeanChanging(value);
					this.SendPropertyChanging();
					this._bean = value;
					this.SendPropertyChanged("bean");
					this.OnbeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closed", DbType="Bit NOT NULL")]
		public bool closed
		{
			get
			{
				return this._closed;
			}
			set
			{
				if ((this._closed != value))
				{
					this.OnclosedChanging(value);
					this.SendPropertyChanging();
					this._closed = value;
					this.SendPropertyChanged("closed");
					this.OnclosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaznatype", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kaznatype
		{
			get
			{
				return this._kaznatype;
			}
			set
			{
				if ((this._kaznatype != value))
				{
					this.OnkaznatypeChanging(value);
					this.SendPropertyChanging();
					this._kaznatype = value;
					this.SendPropertyChanged("kaznatype");
					this.OnkaznatypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountDes", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AccountDes
		{
			get
			{
				return this._AccountDes;
			}
			set
			{
				if ((this._AccountDes != value))
				{
					this.OnAccountDesChanging(value);
					this.SendPropertyChanging();
					this._AccountDes = value;
					this.SendPropertyChanged("AccountDes");
					this.OnAccountDesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CDkaznatype")]
	public partial class CDkaznatype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _kaznatypeid;
		
		private string _kaznatype;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkaznatypeidChanging(byte value);
    partial void OnkaznatypeidChanged();
    partial void OnkaznatypeChanging(string value);
    partial void OnkaznatypeChanged();
    #endregion
		
		public CDkaznatype()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaznatypeid", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte kaznatypeid
		{
			get
			{
				return this._kaznatypeid;
			}
			set
			{
				if ((this._kaznatypeid != value))
				{
					this.OnkaznatypeidChanging(value);
					this.SendPropertyChanging();
					this._kaznatypeid = value;
					this.SendPropertyChanged("kaznatypeid");
					this.OnkaznatypeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaznatype", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kaznatype
		{
			get
			{
				return this._kaznatype;
			}
			set
			{
				if ((this._kaznatype != value))
				{
					this.OnkaznatypeChanging(value);
					this.SendPropertyChanging();
					this._kaznatype = value;
					this.SendPropertyChanged("kaznatype");
					this.OnkaznatypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTBLTRAANSDETAILS")]
	public partial class vTBLTRAANSDETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TRANSID;
		
		private byte _YearID;
		
		private string _YearName;
		
		private System.Nullable<System.DateTime> _KIEDDATE;
		
		private string _KIEDDESC;
		
		private int _AccountId;
		
		private System.Nullable<double> _Madeen;
		
		private System.Nullable<double> _Daien;
		
		private string _kieddes;
		
		private string _AccountDes;
		
		private string _AccNatueName;
		
		private string _MostandNo;
		
		private byte _TNO;
		
		private System.Nullable<int> _KIEDNO;
		
		private System.Nullable<int> _KIEDDAFTRYNO;
		
		private System.Nullable<bool> _trhel;
		
		private int _userin;
		
		private System.DateTime _datein;
		
		private string _UserName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRANSIDChanging(int value);
    partial void OnTRANSIDChanged();
    partial void OnYearIDChanging(byte value);
    partial void OnYearIDChanged();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnKIEDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKIEDDATEChanged();
    partial void OnKIEDDESCChanging(string value);
    partial void OnKIEDDESCChanged();
    partial void OnAccountIdChanging(int value);
    partial void OnAccountIdChanged();
    partial void OnMadeenChanging(System.Nullable<double> value);
    partial void OnMadeenChanged();
    partial void OnDaienChanging(System.Nullable<double> value);
    partial void OnDaienChanged();
    partial void OnkieddesChanging(string value);
    partial void OnkieddesChanged();
    partial void OnAccountDesChanging(string value);
    partial void OnAccountDesChanged();
    partial void OnAccNatueNameChanging(string value);
    partial void OnAccNatueNameChanged();
    partial void OnMostandNoChanging(string value);
    partial void OnMostandNoChanged();
    partial void OnTNOChanging(byte value);
    partial void OnTNOChanged();
    partial void OnKIEDNOChanging(System.Nullable<int> value);
    partial void OnKIEDNOChanged();
    partial void OnKIEDDAFTRYNOChanging(System.Nullable<int> value);
    partial void OnKIEDDAFTRYNOChanged();
    partial void OntrhelChanging(System.Nullable<bool> value);
    partial void OntrhelChanged();
    partial void OnuserinChanging(int value);
    partial void OnuserinChanged();
    partial void OndateinChanging(System.DateTime value);
    partial void OndateinChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public vTBLTRAANSDETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TRANSID
		{
			get
			{
				return this._TRANSID;
			}
			set
			{
				if ((this._TRANSID != value))
				{
					this.OnTRANSIDChanging(value);
					this.SendPropertyChanging();
					this._TRANSID = value;
					this.SendPropertyChanged("TRANSID");
					this.OnTRANSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearID", DbType="TinyInt NOT NULL")]
		public byte YearID
		{
			get
			{
				return this._YearID;
			}
			set
			{
				if ((this._YearID != value))
				{
					this.OnYearIDChanging(value);
					this.SendPropertyChanging();
					this._YearID = value;
					this.SendPropertyChanged("YearID");
					this.OnYearIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(30)")]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KIEDDATE
		{
			get
			{
				return this._KIEDDATE;
			}
			set
			{
				if ((this._KIEDDATE != value))
				{
					this.OnKIEDDATEChanging(value);
					this.SendPropertyChanging();
					this._KIEDDATE = value;
					this.SendPropertyChanged("KIEDDATE");
					this.OnKIEDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDESC", DbType="NVarChar(100)")]
		public string KIEDDESC
		{
			get
			{
				return this._KIEDDESC;
			}
			set
			{
				if ((this._KIEDDESC != value))
				{
					this.OnKIEDDESCChanging(value);
					this.SendPropertyChanging();
					this._KIEDDESC = value;
					this.SendPropertyChanged("KIEDDESC");
					this.OnKIEDDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madeen", DbType="Float")]
		public System.Nullable<double> Madeen
		{
			get
			{
				return this._Madeen;
			}
			set
			{
				if ((this._Madeen != value))
				{
					this.OnMadeenChanging(value);
					this.SendPropertyChanging();
					this._Madeen = value;
					this.SendPropertyChanged("Madeen");
					this.OnMadeenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daien", DbType="Float")]
		public System.Nullable<double> Daien
		{
			get
			{
				return this._Daien;
			}
			set
			{
				if ((this._Daien != value))
				{
					this.OnDaienChanging(value);
					this.SendPropertyChanging();
					this._Daien = value;
					this.SendPropertyChanged("Daien");
					this.OnDaienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kieddes", DbType="NVarChar(50)")]
		public string kieddes
		{
			get
			{
				return this._kieddes;
			}
			set
			{
				if ((this._kieddes != value))
				{
					this.OnkieddesChanging(value);
					this.SendPropertyChanging();
					this._kieddes = value;
					this.SendPropertyChanged("kieddes");
					this.OnkieddesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountDes", DbType="NVarChar(150)")]
		public string AccountDes
		{
			get
			{
				return this._AccountDes;
			}
			set
			{
				if ((this._AccountDes != value))
				{
					this.OnAccountDesChanging(value);
					this.SendPropertyChanging();
					this._AccountDes = value;
					this.SendPropertyChanged("AccountDes");
					this.OnAccountDesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNatueName", DbType="NVarChar(20)")]
		public string AccNatueName
		{
			get
			{
				return this._AccNatueName;
			}
			set
			{
				if ((this._AccNatueName != value))
				{
					this.OnAccNatueNameChanging(value);
					this.SendPropertyChanging();
					this._AccNatueName = value;
					this.SendPropertyChanged("AccNatueName");
					this.OnAccNatueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MostandNo", DbType="NVarChar(50)")]
		public string MostandNo
		{
			get
			{
				return this._MostandNo;
			}
			set
			{
				if ((this._MostandNo != value))
				{
					this.OnMostandNoChanging(value);
					this.SendPropertyChanging();
					this._MostandNo = value;
					this.SendPropertyChanged("MostandNo");
					this.OnMostandNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TNO", DbType="TinyInt NOT NULL")]
		public byte TNO
		{
			get
			{
				return this._TNO;
			}
			set
			{
				if ((this._TNO != value))
				{
					this.OnTNOChanging(value);
					this.SendPropertyChanging();
					this._TNO = value;
					this.SendPropertyChanged("TNO");
					this.OnTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDNO", DbType="Int")]
		public System.Nullable<int> KIEDNO
		{
			get
			{
				return this._KIEDNO;
			}
			set
			{
				if ((this._KIEDNO != value))
				{
					this.OnKIEDNOChanging(value);
					this.SendPropertyChanging();
					this._KIEDNO = value;
					this.SendPropertyChanged("KIEDNO");
					this.OnKIEDNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIEDDAFTRYNO", DbType="Int")]
		public System.Nullable<int> KIEDDAFTRYNO
		{
			get
			{
				return this._KIEDDAFTRYNO;
			}
			set
			{
				if ((this._KIEDDAFTRYNO != value))
				{
					this.OnKIEDDAFTRYNOChanging(value);
					this.SendPropertyChanging();
					this._KIEDDAFTRYNO = value;
					this.SendPropertyChanged("KIEDDAFTRYNO");
					this.OnKIEDDAFTRYNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trhel", DbType="Bit")]
		public System.Nullable<bool> trhel
		{
			get
			{
				return this._trhel;
			}
			set
			{
				if ((this._trhel != value))
				{
					this.OntrhelChanging(value);
					this.SendPropertyChanging();
					this._trhel = value;
					this.SendPropertyChanged("trhel");
					this.OntrhelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userin", DbType="Int NOT NULL")]
		public int userin
		{
			get
			{
				return this._userin;
			}
			set
			{
				if ((this._userin != value))
				{
					this.OnuserinChanging(value);
					this.SendPropertyChanging();
					this._userin = value;
					this.SendPropertyChanged("userin");
					this.OnuserinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datein", DbType="DateTime NOT NULL")]
		public System.DateTime datein
		{
			get
			{
				return this._datein;
			}
			set
			{
				if ((this._datein != value))
				{
					this.OndateinChanging(value);
					this.SendPropertyChanging();
					this._datein = value;
					this.SendPropertyChanged("datein");
					this.OndateinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
